name: cine_quest_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  faker: ^2.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
